version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: questionnaire_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: questionnaire_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d questionnaire_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: questionnaire_backend
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/questionnaire_db
    volumes:
      - ./backend:/app
      - ./dati:/app/dati
    ports:
      - "8118:8000"
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: questionnaire_frontend
    environment:
      VITE_API_URL: http://192.168.129.14:8118
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5180:5173"
    depends_on:
      - backend
    command: npm run dev -- --host

volumes:
  postgres_data:
